### ISSUE TITLE
Android version

### ISSUE THREAD

**Issue by 4face-studi0** [4face-studi0/CineScout#3]
- [x] Compose setup ( #10 )
- [x] Theme setup ( #14 )
- [x] Navigator ( #15 )
- [x] Base UI ( #17 )
- [x] Movie Details UI ( #20  )
- [x] Search complete UI ( #21 ) )
- [x] Suggestions complete UI ( #26 )
